"""NuExtract-2.0-8B baseline: single-shot, image-based structured extraction.

Unlike MeasurementLM (which reads OCR'd `<page>/<table>` tagged text) and unlike
Ablation 1 (which is also single-shot but text-only), this baseline sends
rendered page images directly to a vision-language model.

NuExtract accepts a JSON extraction schema but has no fields for freeform
instructions alongside the structural outline (only `template` and optional few-shot
`examples`).

The template's image branch also only ever emits *one* image placeholder per
message — `{%- if ... not ns2.found_image -%}` short-circuits after the first
`image_url` block, regardless of how many are attached — so a whole multi-page
document cannot be sent in a single call. Requests are therefore dispatched
per (page, attribute): `fit()`'s `_deduplicate()` step merges the resulting
records back into one set of measurements per document.

Extraction is split one attribute at a time, the same way the GLiNER2 and
ChatExtract baselines run (see `measurementlm_gliner.py`, `measurementlm_chatextract.py`):
`attribute` is fixed by the caller for each call and assigned to every
returned record programmatically, never generated by the model. This isn't
just a schema simplification — it closes a real hole. NuExtract's `template`
enum (e.g. `"attribute": ["tn", "tp", ...]`) is only interpolated into the
prompt as text by its custom chat template; it is not a decoding-time
constraint. The actual constraint enforced by vLLM's guided decoding is
`response_format`, built from `direct_extraction_schema`, where `attribute`
was typed as a plain `str` — so nothing stopped the model from emitting
off-vocabulary attribute values. Asking for one fixed attribute per call
removes the field (and the failure mode) entirely rather than trying to
constrain it harder.

Each dataset's `DatasetConfig.nuextract_examples` may show multiple
attributes per passage (see individual dataset configs); `_extract_records`
filters each example down to the attribute in play for a given call and
strips the (now nonexistent) `attribute` key from its items — including down
to zero items, which is itself a useful negative example: it shows the model
that a passage about other attributes should yield no output for this one.

Dropping `attribute` removes the enum entirely, which also removes the only
place the *vocabulary* ("tn", "tp", "chla", ...) was spelled out for the
model. Since NuExtract's template has no separate description field, the
generic key `"value"` alone doesn't say what quantity to extract — that
would leave a call disambiguated only by whichever few-shot example happens
to be attached, which is empty for any attribute the examples don't cover.
`_value_field_key()` recovers that signal the way NuExtract expects: it
folds `attribute_info_dict[attr]["description"]` into the JSON key itself
(e.g. `"ph: pH of the water, i.e. ..."` instead of `"value"`), so the
per-call template and its guided-decoding schema both carry the attribute's
meaning even without a dedicated instructions channel. `_schema_for_attribute`
implements this via a Pydantic field alias, so parsed responses still come
back keyed as plain `"value"` for the rest of the pipeline.
"""

import json
from functools import partial
from pathlib import Path

from pydantic import Field, create_model

from .measurementlm import MeasurementLM, response_validator


def _value_field_key(attribute_name: str, attribute_info_dict: dict) -> str:
    """Build the JSON key standing in for `value` on this attribute's call.

    NuExtract's template has no separate field-description mechanism — only
    a field name and a type — so the attribute's description is folded into
    the key itself (see module docstring) rather than lost when `attribute`
    is dropped from the schema.
    """
    description = attribute_info_dict[attribute_name].get("description", "")
    return f"{attribute_name}: {description}" if description else attribute_name


def _build_template(direct_extraction_schema, value_field_key: str) -> dict:
    """Convert a flat direct-extraction schema into a NuExtract JSON template.

    Every field is typed as `verbatim-string` (copy exactly from the document)
    except `attribute`, which is omitted, and `value`, which is renamed to
    `value_field_key` so the key itself tells the model which attribute this
    call is for (see module docstring).
    """
    item_template = {}
    for field_name in direct_extraction_schema.model_fields:
        if field_name == "attribute":
            continue
        key = value_field_key if field_name == "value" else field_name
        item_template[key] = "verbatim-string"
    return {"items": [item_template]}


def _schema_for_attribute(direct_extraction_schema, value_field_key: str):
    """Pydantic model mirroring direct_extraction_schema minus `attribute`,
    with `value` aliased to `value_field_key`.

    Used to build the guided-decoding `response_format` for a single-attribute
    NuExtract call, so the enforced JSON schema matches the template's field
    names exactly. The alias is internal to the wire format: `response_validator`
    calls `model_dump()` (by_alias=False), so parsed records still come back
    keyed as plain `"value"`.
    """
    fields = {}
    for name, field in direct_extraction_schema.model_fields.items():
        if name == "attribute":
            continue
        default = ... if field.is_required() else field.default
        if name == "value":
            fields[name] = (field.annotation, Field(default, alias=value_field_key))
        else:
            fields[name] = (field.annotation, default)
    return create_model(f"{direct_extraction_schema.__name__}ForAttribute", **fields)


def _filter_examples_for_attribute(
    examples: list[dict] | None, attribute_name: str, value_field_key: str
) -> list[dict]:
    """Narrow dataset-level few-shot examples down to one attribute's items.

    Strips the `attribute` key from kept items and renames `value` to
    `value_field_key` so example outputs match the per-attribute template
    used at call time (see module docstring).
    """
    filtered = []
    for example in examples or []:
        items = json.loads(example["output"])["items"]
        kept_items = []
        for item in items:
            if item.get("attribute") != attribute_name:
                continue
            renamed = {k: v for k, v in item.items() if k not in ("attribute", "value")}
            renamed[value_field_key] = item["value"]
            kept_items.append(renamed)
        filtered.append({"input": example["input"], "output": json.dumps({"items": kept_items})})
    return filtered


class MeasurementLMNuExtract(MeasurementLM):
    """Single-shot image-based extraction baseline using NuExtract-2.0-8B."""

    def __init__(
        self,
        *args,
        direct_extraction_schema=None,
        examples: list[dict] | None = None,
        max_concurrent: int = 16,
        max_images_per_document: int = 45,
        use_extra_body: bool = True,
        **kwargs,
    ):
        super().__init__(*args, max_concurrent=max_concurrent, use_extra_body=use_extra_body, **kwargs)
        if direct_extraction_schema is None:
            raise ValueError(
                "direct_extraction_schema must be set for MeasurementLMNuExtract. "
                "Use the same schema defined in the dataset config for Ablation 1."
            )
        self.direct_extraction_schema = direct_extraction_schema
        self.examples = examples
        self.max_images_per_document = max_images_per_document

    # -----------------------------------------------------------------------
    # Single extraction step: extract all records directly from page images
    # -----------------------------------------------------------------------

    def _extract_records(self, processed_pdf_dirs: list[str]) -> list[dict]:
        """Extract all measurement records from each document's page images.

        Dispatches one request per (page, attribute) — NuExtract's chat
        template only supports a single image per message, and attribute is
        now fixed per call rather than generated (see module docstring) — and
        tags each resulting record with its source document and attribute so
        `fit()`'s `_deduplicate()` step can merge records back into one set
        of measurements per document.

        Args:
            processed_pdf_dirs: Paths to pre-processed image directories, one
                per document (in the same order as `self.data`), each
                containing `{page_index}.b64` files from `process_pdfs.py`.

        Returns:
            List of records suitable for `_deduplicate()`.
        """
        # NuExtract's chat template only accepts a single image content block
        # per message (plus an optional literal "<image>" text sentinel) —
        # any other text block, or any additional image, makes it silently
        # drop the image placeholder(s). The schema itself is sent out-of-band
        # via extra_body below, so each message here is exactly one image;
        # the same set of page messages is reused for every attribute.
        messages: list[list[dict]] = []
        message_doc_indices: list[int] = []
        message_page_indices: list[int] = []
        for doc_idx, doc_dir in enumerate(processed_pdf_dirs):
            doc_path = Path(doc_dir)
            if not doc_path.exists():
                raise FileNotFoundError(
                    f"Processed PDF directory not found: {doc_dir}\n"
                    f"Run 'python experiments/process_pdfs.py' first."
                )
            page_files = sorted(doc_path.glob("*.b64"), key=lambda p: int(p.stem))
            if len(page_files) > self.max_images_per_document:
                print(
                    f"WARNING: {doc_dir} has {len(page_files)} pages, exceeding "
                    f"max_images_per_document={self.max_images_per_document}. "
                    f"Only the first {self.max_images_per_document} pages will be sent."
                )
                page_files = page_files[: self.max_images_per_document]

            for page_file in page_files:
                image_b64 = page_file.read_text().strip()
                content = [{
                    "type": "image_url",
                    "image_url": {"url": f"data:image/png;base64,{image_b64}"},
                }]
                messages.append([{"role": "user", "content": content}])
                message_doc_indices.append(doc_idx)
                # page_file.stem is the 0-indexed page number, matching the OCR
                # <page number="N"> tags the judge uses to limit its context.
                message_page_indices.append(int(page_file.stem))

        records: list[dict] = []
        for attr_name in self.attribute_info_dict:
            value_field_key = _value_field_key(attr_name, self.attribute_info_dict)
            template_json = json.dumps(
                _build_template(self.direct_extraction_schema, value_field_key), indent=2
            )
            AttributeSchema = _schema_for_attribute(self.direct_extraction_schema, value_field_key)
            DirectExtractionList = create_model(
                "DirectExtractionList",
                items=(list[AttributeSchema], ...),
            )
            response_format = {
                "type": "json_schema",
                "json_schema": {
                    "name": "direct_extraction_list",
                    "schema": DirectExtractionList.model_json_schema(),
                },
            }

            chat_template_kwargs = {"template": template_json}
            attr_examples = _filter_examples_for_attribute(self.examples, attr_name, value_field_key)
            if attr_examples:
                chat_template_kwargs["examples"] = attr_examples
            extra_body = {"chat_template_kwargs": chat_template_kwargs}

            response_texts = self._call_batch(
                messages,
                response_format=response_format,
                max_tokens=4096,
                max_retries=4,
                validator=partial(response_validator, DirectExtractionList),
                timeout=300.0,
                extra_body=extra_body,
            )

            for msg_idx, r in enumerate(response_texts):
                doc_idx = message_doc_indices[msg_idx]
                page_number = message_page_indices[msg_idx]
                try:
                    resp_validated = response_validator(DirectExtractionList, r)
                except Exception as e:
                    print(f"Validation error in NuExtract response (doc {doc_idx}, attribute {attr_name}, msg {msg_idx}): {e}")
                    print(f"Response text: {r}")
                    resp_validated = {"items": []}

                for item_idx, item in enumerate(resp_validated["items"]):
                    if item.get("value") is None:
                        continue
                    entity_id = f"doc_{doc_idx}_msg_{msg_idx}_attr_{attr_name}_entity_{item_idx}"
                    records.append(
                        self.data[doc_idx] | item | {
                            "attribute": attr_name,
                            "entity_id": entity_id,
                            "attribute_terms": [],
                            "page_number": page_number,
                        }
                    )

        return records

    # -----------------------------------------------------------------------
    # Full pipeline (single extraction step + programmatic dedup)
    # -----------------------------------------------------------------------

    def fit(self, processed_pdf_dirs: list[str]) -> list[dict]:
        """Run the NuExtract baseline on the given documents' page images.

        Deliberately skips `_standardize()` (an LLM normalization pass) so the
        comparison isn't blended with an extra MeasurementLM-specific LLM
        call; `_deduplicate()` is purely programmatic and is applied for a
        fair, non-conflating cleanup of near-duplicate mentions.
        """
        self.data = [{"document_id": i} for i in range(len(processed_pdf_dirs))]
        self.data = self._extract_records(processed_pdf_dirs)
        self.data = self._deduplicate(self.data)
        return self.data
